Python/django/belt_reviewer/apps/belt_review_app/urls.py
from django.conf.urls import url
from . import views

app_name = 'review'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add, name='add'),
    url(r'^new_review/$', views.new_review, name='new_review'),
    # url(r'^new_review/(?P<id>\d+)$', views.new_review, name='new_review'),
    # url(r'^delete/(?P<id>\d+)$', views.delete, name='delete'),
]

Python/django/belt_reviewer/apps/login_and_registration_app/urls.py
from django.conf.urls import url
from . import views

app_name = 'auth'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^registration$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
]

Python/django/belt_reviewer/belt_reviewer/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^review/', include('apps.belt_review_app.urls', namespace='review') ),
    url(r'^', include('apps.login_and_registration_app.urls', namespace='auth') ),
]

Python/django/belt_reviewer/apps/belt_review_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from ..login_and_registration_app.models import User


# Create your models here.
class ReviewManager(models.Manager):
    def create_review(self,data):
        print "creating new review"
        print "*************"
        print data, "<<--here is the data from the validations and/or database"
        # print "$$$$$$$$$$$$", data['user_id']

        # print "user_id!!!!!!!!!!:", User.objects.get(user_id=data['user_id'])
        errors = []
        #validate length of review (>1 char/ < 300)
        if len(data['review']) < 1:
            print "Review cannot be empty"
            errors.append("Review cannot be empty")
        if len(data['title']) < 1:
            print "Title cannot be empty"
            errors.append("Review cannot be empty")
        if len(data['review']) > 300:
            print "Review cannot be longer than 300 characters"
            errors.append("Review cannot be longer than 300 characters")
        if len(data['author']) < 1:
            print "Author cannot be empty"
            errors.append("Review cannot be empty")
        if len(data['author']) > 150:
            print "Author's name cannot exceed 150 characters"
            errors.append("Author's name cannot exceed 150 characters")
        if errors:
            return(False,errors)
        else:
            print "Adding data to database"
            # user_id = User.objects.get(id=data['user_id']) #get id from Login and reg models.py
            # user = User.objects.get(user_id=data['user_id']) #get id from Login and reg models.py

            new_review = Review.objects.create(
                review = data['review'],
                rating = data['rating'],
                # user = user,
            )
    # def get_rating(request):
    #     new_rating = Review.objects.get(rating=data['rating'])

            print "data was added!"
            return(True,new_review)

class BookManager(models.Manager):
    pass
class AuthorManager(models.Manager):
    pass

class Review(models.Model):
    review = models.TextField()
    rating = models.IntegerField(default=0)
    user_id = models.ForeignKey(User, null=True)
    #book_id = models.ForeignKey(Book,on_delete=models.CASCADE)<------ADD
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = ReviewManager()

class Book(models.Model):
    title = models.CharField(max_length = 300)
    #review_id = models.ForeignKey(Review, on_delete=models.CASCADE) <---- REMOVE 
    #author_id = models.ForeignKey(Author,on_delete=models.CASCADE) <------ADD 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = BookManager()

class Author(models.Model):
    name = models.CharField(max_length = 150)
    #book_id = models.ForeignKey(Book,on_delete=models.CASCADE) <------REMOVE 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = AuthorManager()

Python/django/belt_reviewer/apps/belt_review_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Review

# Create your views here.
def index(request):
    print "INDEX METHOD"
    print "************"

    return render(request, 'belt_review_app/index.html')

def add(request):
    print "ADD METHOD"
    print "************"
    context = {
        'all_reviews': Review.objects.all()
    }
    print context, "<------- CONTEXT"
    return render(request, 'belt_review_app/add.html', context)

def new_review(request):
    print "NEW REVIEW METHOD"
    print "************"
    if request.method == 'POST':
        print "request.POST:",request.POST

        valid, data = Review.objects.create_review(request.POST)

        if valid == True:
            print "Added review to database"
            print "***********************"
        else:
            for err in data:
                messages.error(request,err)
                return redirect('review:add')
    else:
        return redirect('auth:index')

    return redirect('review:index') #send user to page of book review

Python/django/belt_reviewer/apps/belt_review_app/templates/belt_review_app/add.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Add Review</title>
    </head>
    <body>
        <h3>Add a New Book Title and a Review</h3>
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>

        <form class="" action="{% url 'review:new_review'  %}" method="post">
            {% csrf_token %}
            <input type="text" name="title" placeholder="Book Title"><br>
            <input type="text" name="author" placeholder="Author"><br>
            <textarea name="review" placeholder="Your review here...."rows="8" cols="80"></textarea><br>
            <label for="">Rating:</label>
            <select name="rating">
                <option value="5">5</option>
                <option value="5">4</option>
                <option value="5">3</option>
                <option value="5">2</option>
                <option value="5">1</option>
            </select>
            <input type="submit" name="" value="Submit">
        </form>
        {% for review in all_reviews %}
        <ul>
            Review: {{review.review}}
            <br>Rating:
            {% for rating in "12345" %}
                "star"
            {% endfor %}<br>
            <!-- {{review.rating}} - -->
            Created at: {{review.created_at}}
            {{review.user}}
            <!-- {{review.updated_at}} -->
        </ul>
        {% endfor %}
        <a href="{% url 'review:index' %}">Back</a>
    </body>
</html>

Python/django/belt_reviewer/apps/belt_review_app/templates/belt_review_app/books.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Books</title>
    </head>
    <body>
        <h1>{{BOOK TITLE}}</h1>
        <p>{{Author Name}}</p>
        <h3>Review</h3>
        <form class="" action="{% url 'review:new_review' %}" method="post">
            {% csrf_token %}
            <textarea name="review" placeholder="Your review here...."rows="8" cols="80"></textarea><br>
            <label for="">rating</label>
            <select name="rating">
                <option value="5">5</option>
                <option value="5">4</option>
                <option value="5">3</option>
                <option value="5">2</option>
                <option value="5">1</option>
            </select> <p>stars</p>
            <input type="submit" name="" value="Submit">
        </form>
        


    </body>
</html>

Python/django/belt_reviewer/apps/belt_review_app/templates/belt_review_app/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Reviewer</title>
    </head>
    <body>
        <div id="container">

            <div id="header">
                <h1>Welcome {{request.session.first_name}} !!!</h1>
                <a href="{% url 'review:add' %}">Add a new review</a>
                <a href="{% url 'auth:logout' %}">Logout</a>
            </div>
            <div id="maincontent">

                <h4>Recent book reviews</h4>

            </div>
            <div id="other">
                <h4>other books with reviews</h4>

            </div>
        </div>
    </body>
</html>